# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMRxDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMRxDemo

pod 'Alamofire'
pod 'RxSwift'
pod 'RxCocoa'
pod 'SDWebImage' 

end
